--liquibase formatted sql

--changeset OATimofeev:001-create-users-table
CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(32)  NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(16)  NOT NULL,
    last_name  VARCHAR(16)  NOT NULL,
    phone      VARCHAR(32)  NOT NULL,
    role       VARCHAR(16)  NOT NULL,
    image      VARCHAR(255),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT users_email_length_check CHECK (LENGTH(email) BETWEEN 4 AND 32),
    CONSTRAINT users_first_name_length_check CHECK (LENGTH(first_name) BETWEEN 2 AND 16),
    CONSTRAINT users_last_name_length_check CHECK (LENGTH(last_name) BETWEEN 2 AND 16)
);

--changeset OATimofeev:002-create-ads-table
CREATE TABLE ads
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   INTEGER      NOT NULL,
    title       VARCHAR(32)  NOT NULL,
    price       INTEGER      NOT NULL,
    description VARCHAR(64)  NOT NULL,
    image       VARCHAR(255) NOT NULL,
    CONSTRAINT ads_author_id_fk FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ads_title_length_check CHECK (LENGTH(title) BETWEEN 4 AND 32),
    CONSTRAINT ads_description_length_check CHECK (LENGTH(description) BETWEEN 8 AND 64),
    CONSTRAINT ads_price_check CHECK (price BETWEEN 0 AND 10000000)
);

--changeset OATimofeev:003-create-comments-table
CREATE TABLE comments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_id      INTEGER     NOT NULL,
    author_id  INTEGER     NOT NULL,
    text       VARCHAR(64) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT comments_ad_id_fk FOREIGN KEY (ad_id) REFERENCES ads (id) ON DELETE CASCADE,
    CONSTRAINT comments_author_id_fk FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT comments_text_length_check CHECK (LENGTH(text) BETWEEN 8 AND 64)
);
